name = "studybuddy"
compatibility_date = "2026-09-12"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "studybuddytool-db"
database_id = "6f51570f-d2c6-413a-9cf9-b6f2dcb43f43"

[[kv_namespaces]]
binding = "ACCOUNT_KV"
id = "6b9abc440d6e44d2babf6d685f9a815e"
